### ISSUE TITLE
Backend tests about Reshape failed

### ISSUE THREAD

**Issue by tungld** [clang-ykt/ONNF#49]
I ran backend tests for reshape but it seems all of them were failed.

Below is output of a simple case `test_reshape_reordered_all_dims_cpu`:
```
======================================================================
FAIL: test_reshape_reordered_all_dims_cpu (__main__.OnnxBackendNodeModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/tungld/dl/onnx/onnx/backend/test/runner/__init__.py", line 248, in device_test_func
    return test_func(*args, device=device, **kwargs)
  File "/home/tungld/dl/onnx/onnx/backend/test/runner/__init__.py", line 313, in run
    atol=model_test.atol)
  File "/home/tungld/dl/onnx/onnx/backend/test/runner/__init__.py", line 178, in assert_similar_outputs
    atol=atol)
  File "/gsa/jpngsa/home/t/u/tungld/dl/anaconda2/envs/python3.6/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 1503, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/gsa/jpngsa/home/t/u/tungld/dl/anaconda2/envs/python3.6/lib/python3.6/site-packages/numpy/testing/_private/utils.py", line 754, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=0.001, atol=1e-07

(shapes (4, 2, 3), (3, 4, 5) mismatch)
 x: array([[[0.548814, 0.715189, 0.602763],
        [0.544883, 0.423655, 0.645894]],
...
 y: array([[[5.488135e-01, 7.151893e-01, 6.027634e-01, 5.448832e-01,
         4.236548e-01],
        [6.458941e-01, 4.375872e-01, 8.917730e-01, 9.636627e-01,...

----------------------------------------------------------------------
Ran 1434 tests in 12.780s

FAILED (failures=1, skipped=1392)
```

@doru1004 Any thought?

**Comment by tungld** [comment]
More investigation.

I realized that the current implementation of reshape lowering does not support type `i64` for its argument `shape` as defined by ONNX here: https://github.com/onnx/onnx/blob/master/docs/Operators.md#reshape

For example: given the following program:
```mlir
func @test_reshape(%arg0 : tensor<?x10xf32>, %arg1 : tensor<4xi64>) -> tensor<*xf32> {
   %0 = "onnx.Reshape"(%arg0, %arg1) : (tensor<?x10xf32>, tensor<4xi64>) -> tensor<*xf32>
   "std.return"(%0) : (tensor<*xf32>) -> ()
}
```

When we ran `onnf-opt ../test/mlir/krnl/reshape.mlir --shape-inference --lower-frontend`, we got this error:
```
../test/mlir/krnl/reshape.mlir:4:8: error: result type 'i64' must be wider than operand type 'i64'
  %0 = "onnx.Reshape"(%arg0, %arg1) : (tensor<?x10xf32>, tensor<4xi64>) -> tensor<*xf32>
```

**Comment by tungld** [comment]
Even with type `i32`, though we could generate bitcode, but we got error when linking:

Input program:
```mlir
func @test_reshape(%arg0 : tensor<?x10xf32>, %arg1 : tensor<4xi32>) -> tensor<*xf32> {
   %0 = "onnx.Reshape"(%arg0, %arg1) : (tensor<?x10xf32>, tensor<4xi32>) -> tensor<*xf32>
   "std.return"(%0) : (tensor<*xf32>) -> ()
}
```
Output with command `onnf --EmitLLVMBC ../test/mlir/krnl/reshape.mlir`:
```
LLVM bitcode written to ./model.bc
```

But we got error when linking:
Command: `llc --filetype=obj model.bc`

Output:
```
Attribute after last parameter!
void (i8*, i8*, i64)* @llvm.memcpy.p0i8.p0i8.i64
Callsite was not defined with variable arguments!
void (i8*, i8*, i64)* @llvm.memcpy.p0i8.p0i8.i64
llc: model.bc: error: input module is broken!
```

**Comment by doru1004** [comment]
Fixes here: https://github.com/clang-ykt/ONNF/pull/53
