### ISSUE TITLE
Entry point patch causes local fail

### ISSUE THREAD

**Issue by doru1004** [clang-ykt/ONNF#83]
Hello,

This patch:

https://github.com/clang-ykt/ONNF/commit/937bbec2655fcc6fae69bb6e07ff8f5843b9d219

is causing this error:

```
sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssserror: 'std.mulf' op requires the same type for all operands and results
Fsssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
======================================================================
FAIL: test_gemm_default_scalar_bias_cpu (__main__.OnnxBackendNodeModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gbercea/PYTHON/anaconda3/lib/python3.7/site-packages/onnx-1.5.0-py3.7-linux-ppc64le.egg/onnx/backend/test/runner/__init__.py", line 248, in device_test_func
    return test_func(*args, device=device, **kwargs)
  File "/home/gbercea/PYTHON/anaconda3/lib/python3.7/site-packages/onnx-1.5.0-py3.7-linux-ppc64le.egg/onnx/backend/test/runner/__init__.py", line 313, in run
    atol=model_test.atol)
  File "/home/gbercea/PYTHON/anaconda3/lib/python3.7/site-packages/onnx-1.5.0-py3.7-linux-ppc64le.egg/onnx/backend/test/runner/__init__.py", line 178, in assert_similar_outputs
    atol=atol)
  File "/home/gbercea/PYTHON/anaconda3/lib/python3.7/site-packages/numpy/testing/nose_tools/utils.py", line 1396, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/home/gbercea/PYTHON/anaconda3/lib/python3.7/site-packages/numpy/testing/nose_tools/utils.py", line 717, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=0.001, atol=1e-07

(shapes (2, 4), (3, 1, 4, 5, 1) mismatch)
 x: array([[3.989205, 4.060195, 4.087317, 4.514287],
       [3.759734, 3.906257, 3.918797, 4.278849]], dtype=float32)
 y: array([[[[[5.488135e-01],
          [7.151893e-01],
          [6.027634e-01],...
```

How is this not failing on the buildbot?

**Comment by tungld** [comment]
Hi Doru,

In my environment, the test `test_gemm_default_scalar_bias_cpu` looks like:
```
module {
  func @main_graph(%arg0: tensor<2x3xf32>, %arg1: tensor<3x4xf32>, %arg2: tensor<f32>) -> tensor<2x4xf32> {
    %0 = "onnx.Gemm"(%arg0, %arg1, %arg2) : (tensor<2x3xf32>, tensor<3x4xf32>, tensor<f32>) -> tensor<2x4xf32>
    return %0 : tensor<2x4xf32>
  }
  "onnx.EntryPoint"() {func = @main_graph, numInputs = 3 : i32, numOutputs = 1 : i32} : () -> ()
}
```

And the test passed. I am using onnx 1.6.0 installed via `pip install onnx`.

**Comment by doru1004** [comment]
So it looks like there is an error with the test then in my version of ONNX. I am using the ONNX that ONNF installs (I think). If there is a version issue with the ONNX submodule we are using can we make sure that we use a newer version if needed?

**Comment by tjingrant** [comment]
@doru1004 that's on my todo list. I'll assign this issue to me. 
Upgrading ONNX in our repo is tricky mainly because right now our repo is locked to a specific ONNX opset version (8) as we did not introduce versioning mechanism, so upgrading will force us to either retarget a different opset version or come up with methods to let two opset versions co-exist.

My current solution is to do `pip install onnx` to install the latest ONNX package for testing purposes. Since this issue only impacts developers of ONNF right now, I haven't put too much thoughts/efforts into solving it and will likely circle back to solving this issue once we solve more pressing problems we are having with ONNX dialect.

**Comment by doru1004** [comment]
> @doru1004 that's on my todo list. I'll assign this issue to me.
> Upgrading ONNX in our repo is tricky mainly because right now our repo is locked to a specific ONNX opset version (8) as we did not introduce versioning mechanism, so upgrading will force us to either retarget a different opset version or come up with methods to let two opset versions co-exist.
> 
> My current solution is to do `pip install onnx` to install the latest ONNX package for testing purposes. Since this issue only impacts developers of ONNF right now, I haven't put too much thoughts/efforts into solving it and will likely circle back to solving this issue once we solve more pressing problems we are having with ONNX dialect.

If the changes are not too big I think it's easier to just move to the new version and use that instead.
